# Generated by Django 2.1.1 on 2018-10-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk', models.CharField(blank=True, max_length=50)),
                ('sender', models.CharField(default='null', max_length=50)),
                ('receiver', models.CharField(default='null', max_length=50)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
