# Generated by Django 2.1.1 on 2018-10-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextMessage',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='message',
            new_name='talk',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='talker',
            new_name='user',
        ),
    ]
