# Generated by Django 2.1.1 on 2018-10-14 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_auto_20181013_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
